### ISSUE TITLE
Speed reset to 1.0 after Track ended

### ISSUE THREAD

**Issue by Awendel** [Anndrey24/VLC_Speed_Controller#1]
When using the AddOn when listening to a Playlist, the given settings only persists the current song,
as soon as the next song comes on, the actual playback reverts back to 1.0, even though it still shows the old value in the interface.

Would maybe also good to somehow sync it better with the inbuilt speed settings.

**Comment by Anndrey24** [comment]
I'll try to solve this as soon as I've got some free time. I've never tried the addon on playlists so thank you for bringing it up!

**Comment by Anndrey24** [comment]
I added a checkbox in the settings window that asks whether speed should be maintained between tracks. Since I haven't been able to find an event handler triggered by a change of playback speed in the Lua scripting API for VLC, I couldn't synchronize the text box with the built-in speed settings unfortunately (e.g. using keyboard shortcuts). However, if you only use the extension's controls, then it should work fine now.
