### ISSUE TITLE
How to write a lua file? Where is the API document.

### ISSUE THREAD

**Issue by xiaoxstz** [Anndrey24/VLC_Speed_Controller#3]
How do you know that there are the functions `vlc.msg.info`, `vlc.var.set` ,and so on?

Is there any VLC API document? Thank you

**Comment by Anndrey24** [comment]
From what I remember, I wasn't able to find all the necessary information in a single file. The most useful web pages I've found are these:  
- https://github.com/videolan/vlc/blob/master/share/lua/README.txt (this is the official documentation)
- https://vlc.verg.ca/ 
- https://gist.github.com/Mefteg/18463a9cd362ff1f1ba6ff57cb7d4547  

I also recommend downloading any add-ons remotely similar to your ideas from https://addons.videolan.org/ and learning from other developers' code since the documentation for Lua scripting for VLC is very limited.
